[package]
name = "authrs"
version = "0.1.0"
authors = ["rob cobb <rwcobbjr@gmail.com>"]
edition = "2018"
description = "authentication and passthrough server"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
